### ISSUE TITLE
What paper did you use to implement graph slam?

### ISSUE THREAD

**Issue by Sollimann** [goktug97/PyGraphSLAM#3]
Hey, what kind of learning resources did you use to implement graph slam? Did you use [this paper](http://robots.stanford.edu/papers/thrun.graphslam.pdf) by S. Thrun, or did you use any other resources? I'm thinking about writing a slam algorithm to use with odometry data (raw) and laser scans in Rust-lang, but I need to gather more learning resources before I get going :) 

Btw, as mentioned I'm planning of implementing a slam algorithm that will compute roomba vacuum cleaner pose (x, y, theta) and also generate a grid map. Available sensors are a RPLidar A1 and raw odometry data from wheel encoders. Any suggestions on what algorithm to use for that? :) 

thanks!

**Comment by goktug97** [comment]
Hello,

I think these were my resources:
- http://www.informatik.uni-freiburg.de/~stachnis/pdf/grisetti10titsmag.pdf
- http://ais.informatik.uni-freiburg.de/teaching/ws20/mapping/
- https://github.com/uoip/g2opy#pose-graph-optimization

Its been a quite sometime since I've looked into any SLAM papers. But usually you will need to solve a nonlinear/linear system to correct robot's position. (Find the best possible combination of positions given noisy sensor data and constraints). It might be another project to write an optimizer on its own but there are probably libraries for Rust to do linear/nonlinear programming. (https://github.com/vbarrielle/sprs, https://github.com/alphaville/optimization-engine)

**Comment by Sollimann** [comment]
Great, thanks for the info!
